#pragma once
#include"Singleton.h"
#define SCREEN_WIDTH 960
#define SCREEN_HEIDHT 640
#define LIMIT_FPS 90

#define PIXEL_WIDTH 16
#define PIXEL_HEIGHT 16

#define MAP_COLLISION_LAYER_NAME "collider"

#define GRAVITY 0.0007f

/*
 *  Player
 */

#define PLAYER_SPRITE_PATH "SpriteSheet_player_12_8.png"
#define PLAYER_SIZE_WIDTH 60
#define PLAYER_SIZE_HEIGHT 60

#define ORIGINAL_PLAYER_SIZE_W 45
#define ORIGINAL_PLAYER_SIZE_H 45
#define ORIGINAL_PLAYER_X 15
#define ORIGINAL_PLAYER_Y 15
#define ORIGINAL_PLAYER_W 18
#define ORIGINAL_PLAYER_H 30
#define ORIGINAL_PLAYER_CROUCH_X 15
#define ORIGINAL_PLAYER_CROUCH_Y 30
#define ORIGINAL_PLAYER_CROUCH_W 18
#define ORIGINAL_PLAYER_CROUCH_H 15

#define PLAYER_MAX_HP 20
#define PLAYER_SPEED_X 0.17f
#define PLAYER_JUMP_FORCE 0.3f

#define PLAYER_BULLET_SPRITE_PATH "Bullet_Player.png"
#define PLAYER_BULLET_WIDTH 7
#define PLAYER_BULLET_HEIGHT 7
#define PLAYER_BULLET_POOL_SIZE 1000
#define PLAYER_BULLET_SPEED 0.25f
#define PLAYER_BULLET_DAMAGE 1
#define PLAYER_SHOOT_COOLDOWN_TIME 300

/*
 *	AR Mob
 */

#define ARMOB_SPRITE_PATH "SpriteSheet_enemy_1_26.png"
#define ARMOB_SIZE_WIDTH 48
#define ARMOB_SIZE_HEIGHT 57

#define ORIGINAL_ARMOB_SIZE_W 32
#define ORIGINAL_ARMOB_SIZE_H 38
#define ORIGINAL_ARMOB_X 9
#define ORIGINAL_ARMOB_Y 10
#define ORIGINAL_ARMOB_W 14
#define ORIGINAL_ARMOB_H 28
#define ORIGINAL_ARMOB_CROUCH_X 9
#define ORIGINAL_ARMOB_CROUCH_Y 10
#define ORIGINAL_ARMOB_CROUCH_W 14
#define ORIGINAL_ARMOB_CROUCH_H 28

#define ARMOB_MAX_HP 3
#define ARMOB_SPEED_X 0.17f
#define ARMOB_JUMP_FORCE 0.3f
#define ARMOB_SIGHT_RANGE 400.0f
#define ARMOB_SHOOT_RANGE 240.0f

#define ARMOB_BULLET_SPRITE_PATH "Bullet_ARMob.png"
#define ARMOB_BULLET_WIDTH 7
#define ARMOB_BULLET_HEIGHT 7
#define ARMOB_BULLET_POOL_SIZE 1000
#define ARMOB_BULLET_SPEED 0.25f
#define ARMOB_BULLET_DAMAGE 1
#define ARMOB_SHOOT_COOLDOWN_TIME 500