//new
#pragma once
#include"Singleton.h"
#define SCREEN_WIDTH 960
#define SCREEN_HEIDHT 640
#define LIMIT_FPS 90

#define PIXEL_WIDTH 16
#define PIXEL_HEIGHT 16

#define MAP_COLLISION_LAYER_NAME "collider"

#define GRAVITY 0.0007f

/*
 *  Player
 */

#define PLAYER_SPRITE_PATH "SpriteSheet_player_12_8.png"
#define PLAYER_SIZE_WIDTH 60
#define PLAYER_SIZE_HEIGHT 60

#define ORIGINAL_PLAYER_SIZE_W 45
#define ORIGINAL_PLAYER_SIZE_H 45
#define ORIGINAL_PLAYER_X 15
#define ORIGINAL_PLAYER_Y 15
#define ORIGINAL_PLAYER_W 17
#define ORIGINAL_PLAYER_H 30
#define ORIGINAL_PLAYER_CROUCH_X 15
#define ORIGINAL_PLAYER_CROUCH_Y 28
#define ORIGINAL_PLAYER_CROUCH_W 17
#define ORIGINAL_PLAYER_CROUCH_H 17

#define PLAYER_MAX_HP 30
#define PLAYER_SPEED_X 0.17f
#define PLAYER_JUMP_FORCE 0.3f

#define PLAYER_BULLET_SPRITE_PATH "Bullet_Player.png"
#define PLAYER_BULLET_WIDTH 9
#define PLAYER_BULLET_HEIGHT 9
#define PLAYER_BULLET_POOL_SIZE 1000
#define PLAYER_BULLET_SPEED 0.25f
#define PLAYER_BULLET_DAMAGE 1
#define PLAYER_SHOOT_COOLDOWN_TIME 300

 /*
  *	AR Mob
  */

#define ARMOB_SPRITE_PATH "SpriteSheet_enemy_1_26.png"
#define ARMOB_SIZE_WIDTH 48
#define ARMOB_SIZE_HEIGHT 57

#define ORIGINAL_ARMOB_SIZE_W 32
#define ORIGINAL_ARMOB_SIZE_H 38
#define ORIGINAL_ARMOB_X 9
#define ORIGINAL_ARMOB_Y 10
#define ORIGINAL_ARMOB_W 16
#define ORIGINAL_ARMOB_H 28
#define ORIGINAL_ARMOB_CROUCH_X 9
#define ORIGINAL_ARMOB_CROUCH_Y 10
#define ORIGINAL_ARMOB_CROUCH_W 16
#define ORIGINAL_ARMOB_CROUCH_H 28

#define ARMOB_MAX_HP 3
#define ARMOB_SPEED_X 0.17f
#define ARMOB_JUMP_FORCE 0.3f
#define ARMOB_SIGHT_RANGE 400.0f
#define ARMOB_SHOOT_RANGE 240.0f

#define ARMOB_BULLET_SPRITE_PATH "Bullet_ARMob.png"
#define ARMOB_BULLET_WIDTH 7
#define ARMOB_BULLET_HEIGHT 7
#define ARMOB_BULLET_POOL_SIZE 1000
#define ARMOB_BULLET_SPEED 0.25f
#define ARMOB_BULLET_DAMAGE 1
#define ARMOB_SHOOT_COOLDOWN_TIME 500

  /*
   *	Sniper Mob
   */

#define SNIPER_SPRITE_PATH "SpriteSheet_SniperMob_1_14.png"
#define SNIPER_SIZE_WIDTH 62
#define SNIPER_SIZE_HEIGHT 62

#define ORIGINAL_SNIPER_SIZE_W 44
#define ORIGINAL_SNIPER_SIZE_H 44
#define ORIGINAL_SNIPER_X 10
#define ORIGINAL_SNIPER_Y 15
#define ORIGINAL_SNIPER_W 25
#define ORIGINAL_SNIPER_H 28
#define ORIGINAL_SNIPER_CROUCH_X 10
#define ORIGINAL_SNIPER_CROUCH_Y 28
#define ORIGINAL_SNIPER_CROUCH_W 25
#define ORIGINAL_SNIPER_CROUCH_H 15

#define SNIPER_MAX_HP 3
#define SNIPER_SPEED_X 0.17f
#define SNIPER_JUMP_FORCE 0.3f
#define SNIPER_SIGHT_RANGE 0.0f
#define SNIPER_SHOOT_RANGE 600.0f

#define SNIPER_BULLET_SPRITE_PATH "Bullet_SniperMob.png"
#define SNIPER_BULLET_WIDTH 5
#define SNIPER_BULLET_HEIGHT 5
#define SNIPER_BULLET_POOL_SIZE 1000
#define SNIPER_BULLET_SPEED 0.5f
#define SNIPER_BULLET_DAMAGE 3
#define SNIPER_SHOOT_COOLDOWN_TIME 1500

   /*
	*	RPG Mob
	*/

#define RPGMOB_SPRITE_PATH "SpriteSheet_RPGmob_1_11.png"
#define RPGMOB_SIZE_WIDTH 62
#define RPGMOB_SIZE_HEIGHT 62

#define ORIGINAL_RPGMOB_SIZE_W 44
#define ORIGINAL_RPGMOB_SIZE_H 44
#define ORIGINAL_RPGMOB_X 10
#define ORIGINAL_RPGMOB_Y 15
#define ORIGINAL_RPGMOB_W 25
#define ORIGINAL_RPGMOB_H 28
#define ORIGINAL_RPGMOB_CROUCH_X 10
#define ORIGINAL_RPGMOB_CROUCH_Y 28
#define ORIGINAL_RPGMOB_CROUCH_W 25
#define ORIGINAL_RPGMOB_CROUCH_H 15

#define RPGMOB_MAX_HP 5
#define RPGMOB_SPEED_X 0.17f
#define RPGMOB_JUMP_FORCE 0.3f
#define RPGMOB_SIGHT_RANGE 0.0f
#define RPGMOB_SHOOT_RANGE 500.0f

#define RPGMOB_BULLET_SPRITE_PATH "Bullet_RPGmob.png"
#define RPGMOB_BULLET_WIDTH 9
#define RPGMOB_BULLET_HEIGHT 9
#define RPGMOB_BULLET_POOL_SIZE 1000
#define RPGMOB_BULLET_SPEED 0.11f
#define RPGMOB_BULLET_DAMAGE 10
#define RPGMOB_SHOOT_COOLDOWN_TIME 5000

	/*
	 *	Boss 1
	 */

#define BOSS1_SPRITE_PATH "SpriteSheet_Boss_1_7.png"
#define BOSS1_SIZE_WIDTH 128
#define BOSS1_SIZE_HEIGHT 128

#define ORIGINAL_BOSS1_SIZE_W 64
#define ORIGINAL_BOSS1_SIZE_H 64
#define ORIGINAL_BOSS1_X 18
#define ORIGINAL_BOSS1_Y 19
#define ORIGINAL_BOSS1_W 27
#define ORIGINAL_BOSS1_H 19
#define ORIGINAL_BOSS1_CROUCH_X 18
#define ORIGINAL_BOSS1_CROUCH_Y 19
#define ORIGINAL_BOSS1_CROUCH_W 27
#define ORIGINAL_BOSS1_CROUCH_H 19

#define BOSS1_MAX_HP 50
#define BOSS1_SPEED_X 0.05f
#define BOSS1_JUMP_FORCE 0.3f
#define BOSS1_SIGHT_RANGE 0.0f
#define BOSS1_SHOOT_RANGE 500.0f

#define BOSS1_BULLET_SPRITE_PATH "Bullet_Boss.png"
#define BOSS1_BULLET_WIDTH 16
#define BOSS1_BULLET_HEIGHT 17
#define BOSS1_BULLET_POOL_SIZE 1000
#define BOSS1_BULLET_SPEED 0.125f
#define BOSS1_BULLET_DAMAGE 1
#define BOSS1_SHOOT_COOLDOWN_TIME 800

//sfx sound
#define Player_Sound "mixkit-game-gun-shot-1662.mp3"
#define ARMob_Sound "mixkit-short-laser-gun-shot-1670.wav"
#define Sniper_Sound "mixkit-laser-cannon-shot-1678.wav"
#define RPG_Sound "rpg.mp3"